# Generated by Django 4.2.24 on 2025-09-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_administrativeboundary_geometry_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('parcel_id', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('area', models.FloatField(blank=True, null=True)),
                ('yield_total', models.FloatField(blank=True, null=True)),
                ('yield_per_ha', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parcel Point',
                'verbose_name_plural': 'Parcel Points',
            },
        ),
    ]
