# Generated by Django 4.2.24 on 2025-09-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parcelpoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcelpoint',
            options={'verbose_name_plural': 'Parcel Points'},
        ),
        migrations.RemoveField(
            model_name='administrativeboundary',
            name='geometry_json',
        ),
        migrations.RemoveField(
            model_name='parcelpoint',
            name='yield_total',
        ),
        migrations.AlterField(
            model_name='parcelpoint',
            name='parcel_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
