# Generated by Django 4.2.24 on 2025-09-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_parcelpoint_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeboundary',
            name='geometry_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelpoint',
            name='yield_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
