# Generated by Django 4.2.24 on 2025-12-11 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_administrativeboundary_geometry_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GapType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Total Exploitable Yield Gap', 'Total Exploitable Yield Gap'), ('Water Limitation Gap', 'Water Limitation Gap'), ('Calibrated vs Water Limited Gap', 'Calibrated vs Water Limited Gap'), ('Fertilizer Response Gap', 'Fertilizer Response Gap'), ('Sowing Date Impact Gap', 'Sowing Date Impact Gap')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Potential', 'Potential'), ('Water Limited', 'Water Limited'), ('Calibrated', 'Calibrated'), ('Unfertilized', 'Unfertilized'), ('Sowing Date', 'Sowing Date'), ('Observed', 'Observed')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Varieties',
            },
        ),
        migrations.CreateModel(
            name='YieldStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField()),
                ('mean', models.FloatField()),
                ('std', models.FloatField(blank=True, null=True)),
                ('min', models.FloatField(blank=True, null=True)),
                ('q25', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('q75', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('data_source', models.CharField(default='Excel Import', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.scenario')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.variety')),
            ],
            options={
                'verbose_name_plural': 'Yield Statistics',
                'indexes': [models.Index(fields=['variety', 'province', 'year', 'scenario'], name='core_yields_variety_cdd7bc_idx'), models.Index(fields=['province', 'year'], name='core_yields_provinc_a91753_idx'), models.Index(fields=['variety', 'year'], name='core_yields_variety_06a88e_idx')],
            },
        ),
        migrations.CreateModel(
            name='GapStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField()),
                ('mean', models.FloatField()),
                ('std', models.FloatField(blank=True, null=True)),
                ('min', models.FloatField(blank=True, null=True)),
                ('q25', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('q75', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('data_source', models.CharField(default='Excel Import', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gap_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gaptype')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.variety')),
            ],
            options={
                'verbose_name_plural': 'Gap Statistics',
                'indexes': [models.Index(fields=['gap_type', 'variety', 'province', 'year'], name='core_gapsta_gap_typ_e4fc1b_idx'), models.Index(fields=['province', 'year'], name='core_gapsta_provinc_621f56_idx'), models.Index(fields=['variety', 'year'], name='core_gapsta_variety_3b3c9d_idx')],
            },
        ),
    ]
