# Generated by Django 4.2.24 on 2025-12-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gaptype_scenario_variety_yieldstatistics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yielddata',
            name='fertilizer_response_gap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='management_gap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='nutrient_gap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='nutrient_limited_yield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='unfertilized_yield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='water_gap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='water_limited_yield',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
